name: Build Windows App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Enable Windows Desktop Support
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/windows/runner/Release

